{"id": "a6b4d691-cbb8-4acb-b17b-d158372dae08", "stack_trace": "Traceback (most recent call last):\n  File \"tests.py\", line 34, in _run_failure_code\n    self._fail()\n  File \"tests.py\", line 27, in _fail\n    y = 5 / 0\nZeroDivisionError: division by zero\n", "error_type": "<class 'ZeroDivisionError'>", "timestamp": "2020-08-18 20:02:08.945872"}
{"id": "ad52be5b-55bd-4fdb-b5a5-0c45df7bfd68", "stack_trace": "Traceback (most recent call last):\n  File \"tests.py\", line 34, in _run_failure_code\n    self._fail()\n  File \"tests.py\", line 27, in _fail\n    y = 5 / 0\nZeroDivisionError: division by zero\n", "error_type": "<class 'ZeroDivisionError'>", "timestamp": "2020-08-18 20:03:47.072936"}
